### ISSUE TITLE
support english calendars

### ISSUE THREAD

**Issue by fehmisener** [TUM-Dev/CalendarProxy#180]
Although my calendar is displayed in English on TUMonline, with the published iCal file, it appears in German in my external calendar. Is it possible to offer an option for an English version of the iCal?

**Comment by CommanderStorm** [comment]
Since the ical currently supplied via TUMonline does not allow us to specify locale (I have checked the expected parameters) => this is not possible on our side.

![image](https://github.com/user-attachments/assets/452526a8-090e-41d4-bc9d-cdfd198fb495)

Issue would need further looking into on the TUMonline side for which I currently don't have the time-resources for.
